GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGFzc2FuIiwiaWF0IjoxNjMzMDIwODAxLCJleHAiOjE2MzMwMjA4MzZ9.5NGXXSlTpPBcDU-Jk4RNMwt1Rs8eGXeQ71aW8AkULPQ

###

DELETE  http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGFzc2FuIiwiaWF0IjoxNjMzMDIwNzA2fQ.xqxNgXQi-wLzA0o0wNGk-QYknzjUVUt1XEnQidHsBck"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGFzc2FuIiwiaWF0IjoxNjMzMDIwNzA2fQ.xqxNgXQi-wLzA0o0wNGk-QYknzjUVUt1XEnQidHsBck"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "Hassan"
}