GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGFzc2FuIiwiaWF0IjoxNjM0NjQyMTg1LCJleHAiOjE2MzQ2NDIyMjB9.SSqxDWgBFaAWJYFjEA2Cm3OaICGJtsPAlDGMeRMjuk4

###

DELETE  http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGFzc2FuIiwiaWF0IjoxNjM0NjQyMDk4fQ.7MF12cqdza9YAs2eOVBIPV-XukC4fCODH_03kh0sAck"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGFzc2FuIiwiaWF0IjoxNjM0NjQyMDk4fQ.7MF12cqdza9YAs2eOVBIPV-XukC4fCODH_03kh0sAck"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "Hassan"
}


### Users requests

GET http://localhost:4000/users


### 
POST http://localhost:4000/users
Content-Type: application/json

{
    "name" : "Hassan",
    "password": "password"
}
